"""Streamlit app for explainable loan default prediction.

Features:
    - CSV upload (with optional sample dataset auto-load)
    - On-demand model training
    - Per-applicant Approve/Reject decision with SHAP local waterfall
    - Global SHAP summary (beeswarm) across all applicants
    - Model evaluation panel (accuracy, F1, precision, recall, ROC-AUC, confusion matrix)
    - Decision-threshold slider for precision/recall trade-off
    - Batch scoring with downloadable results CSV
    - Auditable PDF decision report per applicant
    - Model card section describing intended use and limitations
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent / "src"))

from model import (
    evaluate,
    predict_batch,
    predict_proba_single,
    train,
)
from explain import explain_global, explain_single, get_feature_names, top_n_features
from report import build_report

# -------------------- page setup --------------------

st.set_page_config(
    page_title="Explainable Loan Default Prediction",
    page_icon="💷",
    layout="wide",
)

st.title("💷 Explainable Loan Default Prediction")
st.markdown(
    "Upload a loan dataset, train a class-balanced Random Forest, and inspect "
    "decisions using **SHAP explanations** — locally per-applicant and globally "
    "across the cohort. Built for the responsible AI workflow used in regulated "
    "consumer lending."
)

SAMPLE_PATH = Path(__file__).parent / "sample_data" / "loans.csv"

# -------------------- sidebar --------------------

st.sidebar.header("Dataset")
data_choice = st.sidebar.radio(
    "Choose data source",
    ["Use bundled sample (recommended)", "Upload my own CSV"],
)

uploaded_file = None
if data_choice == "Upload my own CSV":
    uploaded_file = st.sidebar.file_uploader("Upload a loan CSV", type=["csv"])

st.sidebar.header("Model")
threshold = st.sidebar.slider(
    "Decision threshold",
    min_value=0.10,
    max_value=0.90,
    value=0.50,
    step=0.01,
    help="Probability above which an applicant is rejected. Lower = stricter (more rejections).",
)

# -------------------- load data --------------------

@st.cache_data
def load_sample() -> pd.DataFrame:
    return pd.read_csv(SAMPLE_PATH)


if data_choice == "Use bundled sample (recommended)":
    if not SAMPLE_PATH.exists():
        st.error(
            "Sample dataset not found. Run `python src/generate_data.py` "
            "to generate it, or upload your own CSV."
        )
        st.stop()
    data = load_sample()
    st.sidebar.success(f"Loaded {len(data):,} rows from bundled sample.")
elif uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.sidebar.success(f"Loaded {len(data):,} rows from upload.")
else:
    st.info("👈 Choose a dataset in the sidebar to begin.")
    with st.expander("📖 What the bundled sample contains"):
        st.markdown(
            """
            The bundled `sample_data/loans.csv` is a fully synthetic dataset of
            2,000 loan applications with realistic feature distributions:

            - **Age**: 21–70
            - **Income**: £12k–£250k (log-normal)
            - **LoanAmount**: correlated with income
            - **CreditScore**: 300–850
            - **MonthsEmployed**: 0–360
            - **NumCreditLines**: 1–12
            - **Default**: target label (≈40% default rate)

            No real personal data is used. The dataset is generated by
            `src/generate_data.py` using a controlled logistic function so
            results are reproducible.
            """
        )
    st.stop()

# Show a preview
with st.expander("👀 Dataset preview"):
    st.dataframe(data.head(10))
    st.caption(f"{data.shape[0]:,} rows × {data.shape[1]} columns")

target_column = st.selectbox(
    "Select target column",
    options=data.columns.tolist(),
    index=data.columns.tolist().index("Default") if "Default" in data.columns else 0,
)

# -------------------- training --------------------

train_button = st.button("🚀 Train model", type="primary")

if train_button:
    with st.spinner("Training Random Forest..."):
        result = train(data, target_column)
        st.session_state["result"] = result
    st.success(f"Trained on {len(result.X_train):,} rows. Test set: {len(result.X_test):,} rows.")

if "result" not in st.session_state:
    st.info("Click **Train model** to fit the pipeline and unlock predictions.")
    st.stop()

result = st.session_state["result"]

# -------------------- evaluation panel --------------------

st.markdown("---")
st.subheader("📊 Model evaluation on held-out test set")

metrics = evaluate(result.pipeline, result.X_test, result.y_test, threshold=threshold)

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Accuracy", f"{metrics.accuracy:.1%}")
m2.metric("F1 score", f"{metrics.f1:.3f}")
m3.metric("Precision", f"{metrics.precision:.3f}")
m4.metric("Recall", f"{metrics.recall:.3f}")
m5.metric("ROC-AUC", f"{metrics.roc_auc:.3f}")

cm_col, info_col = st.columns([1, 1])
with cm_col:
    fig_cm, ax_cm = plt.subplots(figsize=(4, 4))
    cm = metrics.confusion
    ax_cm.imshow(cm, cmap="Blues")
    ax_cm.set_xticks([0, 1])
    ax_cm.set_yticks([0, 1])
    ax_cm.set_xticklabels(["Approve", "Reject"])
    ax_cm.set_yticklabels(["Approve", "Reject"])
    ax_cm.set_xlabel("Predicted")
    ax_cm.set_ylabel("Actual")
    ax_cm.set_title(f"Confusion matrix (threshold = {threshold:.2f})")
    for i in range(2):
        for j in range(2):
            ax_cm.text(j, i, str(cm[i, j]), ha="center", va="center",
                       color="white" if cm[i, j] > cm.max() / 2 else "black",
                       fontsize=14, fontweight="bold")
    st.pyplot(fig_cm)
with info_col:
    st.markdown(
        f"""
        **At threshold {threshold:.2f}:**
        - {metrics.confusion[0, 0]} true approvals (correct accepts)
        - {metrics.confusion[1, 1]} true rejections (correct denials)
        - {metrics.confusion[0, 1]} false rejections (lost revenue)
        - {metrics.confusion[1, 0]} false approvals (default risk)

        Move the **threshold slider** in the sidebar to explore the
        precision/recall trade-off. In real lending, the threshold is
        tuned to the lender's risk appetite — stricter for unsecured
        personal loans, more permissive for collateralised mortgages.
        """
    )

# -------------------- single-applicant decision --------------------

st.markdown("---")
st.subheader("🔍 Decision for a single applicant")

row_index = st.number_input(
    "Test set row index",
    min_value=0,
    max_value=len(result.X_test) - 1,
    value=0,
    step=1,
)

sample = result.X_test.iloc[row_index:row_index + 1]
proba = predict_proba_single(result.pipeline, sample)
decision = "REJECT" if proba >= threshold else "APPROVE"

col_a, col_b = st.columns([1, 2])
with col_a:
    if decision == "APPROVE":
        st.success(f"✅ APPROVE — default risk {proba:.1%}")
    else:
        st.error(f"❌ REJECT — default risk {proba:.1%}")
with col_b:
    st.dataframe(sample, use_container_width=True)

# Local SHAP
st.markdown("##### Why this decision? (local SHAP)")
local_exp = explain_single(result.pipeline, sample)
fig_local = plt.figure(figsize=(8, 4))
shap.plots.waterfall(local_exp, max_display=10, show=False)
st.pyplot(fig_local)

# Plain-English reasons
top_local = top_n_features(local_exp, n=3)
reason_text = (
    f"The loan was **{'approved' if decision == 'APPROVE' else 'rejected'}** "
    f"primarily because of **{top_local[0][0]}** and **{top_local[1][0]}**."
)
st.info(reason_text)

# PDF report
pdf_bytes = build_report(
    applicant_features=sample,
    decision=decision,
    probability=proba,
    top_reasons=top_local,
)
st.download_button(
    label="📄 Download PDF decision report",
    data=pdf_bytes,
    file_name=f"loan_decision_row_{row_index}.pdf",
    mime="application/pdf",
)

# -------------------- global SHAP --------------------

st.markdown("---")
st.subheader("🌐 Global feature importance (cohort SHAP)")
st.caption("Computed on a sample of up to 500 test-set rows for responsiveness.")

global_exp = explain_global(result.pipeline, result.X_test, max_samples=500)
fig_global = plt.figure(figsize=(8, 5))
shap.plots.beeswarm(global_exp, max_display=10, show=False)
st.pyplot(fig_global)

# -------------------- batch scoring --------------------

st.markdown("---")
st.subheader("📦 Batch scoring")
st.markdown(
    "Score the entire test set at the current threshold and download as CSV. "
    "Mirrors how lenders run overnight batch decisions over an application backlog."
)

if st.button("Run batch scoring"):
    batch_results = predict_batch(result.pipeline, result.X_test, threshold=threshold)
    st.dataframe(batch_results.head(20), use_container_width=True)
    csv_bytes = batch_results.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="⬇️ Download full batch results (CSV)",
        data=csv_bytes,
        file_name="batch_decisions.csv",
        mime="text/csv",
    )

# -------------------- model card --------------------

st.markdown("---")
st.subheader("📋 Model card")
st.markdown(
    """
    **Intended use**
    Decision-support tool for human loan officers in consumer credit. Each prediction
    is paired with a SHAP explanation to support both internal audit and adverse-action
    communication to applicants.

    **Training data**
    Synthetic dataset of 2,000 applications with feature distributions inspired by
    public lending datasets. No real personal data used. The default label is a
    logistic function of loan-to-income ratio, credit score, employment length,
    and number of credit lines.

    **Model**
    Class-balanced Random Forest (300 trees, max depth 8) inside a scikit-learn
    Pipeline with a ColumnTransformer for one-hot encoding of categorical features.

    **Explainability**
    SHAP TreeExplainer for both local (per-applicant waterfall) and global (cohort
    beeswarm) explanations. Decision thresholds are adjustable to reflect different
    risk appetites.

    **Limitations**
    - SHAP attributions can be unstable for rare or extreme applicant profiles.
    - The model is trained on synthetic data and is not suitable for production use.
    - Income, employment, and geography features can act as proxies for protected
      characteristics; bias and fairness testing would be required before deployment.

    **Regulatory context**
    Under UK consumer credit and equality law, applicants have the right to a
    meaningful explanation of automated decisions and to request a manual review.
    The downloadable PDF report supports both requirements.
    """
)

# -------------------- footer --------------------

st.markdown("---")
st.caption(
    "Built by Salman Khan · MSc Artificial Intelligence, Ulster University · "
    "[GitHub repo](https://github.com/mohammedsalmankhan/loan-default-shap)"
)
